"""Application constants."""

# QML Registration
QML_IMPORT_NAME = "DBToolkit"
QML_IMPORT_MAJOR_VERSION = 1

# Cache Settings
DEFAULT_CACHE_TTL = 300  # 5 minutes

# UI Constants
DEFAULT_WINDOW_WIDTH = 1200
DEFAULT_WINDOW_HEIGHT = 800
CONNECTION_PANEL_WIDTH = 300
SCHEMA_PANEL_WIDTH = 350

# UI Styling
BORDER_RADIUS = 12
CARD_SHADOW_OFFSET = 2
ANIMATION_DURATION = 200
HOVER_OPACITY = 0.8

# Database Connection Timeouts
DEFAULT_CONNECTION_TIMEOUT = 30
DEFAULT_QUERY_TIMEOUT = 60

# Query Execution
MAX_RESULT_ROWS = 1000
QUERY_HISTORY_LIMIT = 100