name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: The app crashes when...
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v0.1.0-beta2
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: OS
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      placeholder: Error logs, screenshots, etc.
