name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What feature would you like?
      description: Describe the feature you want
      placeholder: I'd like to be able to...
    validations:
      required: true

  - type: textarea
    id: why
    attributes:
      label: Why do you need this?
      description: What problem does it solve?
      placeholder: This would help me...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional info
      placeholder: Mockups, examples, etc.
